# Generated by Django 4.0.4 on 2022-07-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('Cod', models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره پروانه')),
                ('name', models.CharField(max_length=50, verbose_name='نام سالن')),
                ('city', models.CharField(default='مشهد', max_length=30, verbose_name='شهر')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='شماره')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, upload_to='cinema_images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'سالن سینما',
                'verbose_name_plural': 'سالن سینما',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('director', models.CharField(max_length=100, verbose_name='کارگردان')),
                ('year', models.IntegerField(verbose_name='سال تولید')),
                ('length', models.IntegerField(verbose_name='مدت زمان فیلم')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('poster', models.ImageField(upload_to='movie_posters/', verbose_name='پوستر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان اغاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('salable_seat', models.IntegerField(verbose_name='صندلی های قابل فروش')),
                ('soled_seat', models.IntegerField(verbose_name='صندلی های فروخته شده')),
                ('status', models.IntegerField(choices=[(1, 'فروش شروع نشده'), (2, 'فروش اغاز شد'), (3, 'بلیط تمام شد'),
                                                        (4, 'فروش به اتمام رسید'), (5, 'فیلم پخش شد'),
                                                        (6, 'فیلم کنسل شد')], verbose_name='وضعیت فروش')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                             to='Ticketing.cinema', verbose_name='سالن سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            to='Ticketing.movie', verbose_name='نام فیلم')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(default=0, verbose_name='تعداد صندلی')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان  خرید')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile',
                                            verbose_name='خریدار')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketing.showtime',
                                               verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
