# Generated by Django 4.0.4 on 2022-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0003_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
