# Generated by Django 4.0.4 on 2022-07-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_birth_date'),
        ('Ticketing', '0004_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(default=0, verbose_name='تعداد صندلی')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان  خرید')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile', verbose_name='خریدار')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ticketing.showtime', verbose_name='سانس')),
            ],
            options={
                'verbose_name': 'بلیط',
                'verbose_name_plural': 'بلیط',
            },
        ),
    ]
