# Generated by Django 4.0.4 on 2022-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Birth_date',
            field=models.DateField(blank=True, verbose_name='تاریخ تولد'),
        ),
    ]
