# Generated by Django 4.0.4 on 2022-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_cod',
            field=models.CharField(max_length=25, verbose_name='رسید پرداخت'),
        ),
    ]
